name: Publish to dev.to

on:
  push:
    branches: [main]
    paths:
      - 'articles/*-devto.md'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish articles to dev.to
        uses: sinedied/publish-devto@v2
        with:
          devto_key: ${{ secrets.DEVTO_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: 'articles/*-devto.md'
          conventional_commits: true
